# docs/Vrui/nav.toml
nav = [
    { "Vrui" = [
        {"Vrui Overview" = "index.md"},
        { "Getting started" = [
            "installation/index.md", 
        { "Installation guide" = "installation/guide.md" }
        ]}
    ]}
]
